name: Publish Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - registry-url: 'https://registry.npmjs.org'
            command: npm publish --access public
            token: ${{ secrets.NPM_TOKEN }}
          - registry-url: 'https://npm.pkg.github.com'
            command: npm publish
            token: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: ${{ matrix.registry-url }}
          scope: '@erc725'
      - run: npm ci
      - run: npm run build
      - run: ${{ matrix.token }}
        env:
          NODE_AUTH_TOKEN: ${{ matrix.token }}
